### PR TITLE
Added message history retrieval

### PR DESCRIPTION
**Pull request by ie208**
Added message history retrieval. Details for clients JSON request (also in the WIKI):

{
	type: "GETCHATHISTORY",
	myUsername: "", 
	theirUsername: "",
	historyDays: ""
}

and the reply from server will include a JSON array:

{
	type: "GETCHATHISTORY", 
	reply:  GETCHATHISTORY + "SUCCESS" or "FAILURE (+ reason if failure), 
	messages: [ 
                   {sender: "senderUsername",
                         recipient: "recipientUsername",
                         message: "msg",
                         timestamp: "yyyy-MM-dd HH:mm:ss"},
                        {sender: "senderUsername",
                         recipient: "recipientUsername",
                         message: "msg",
                         timestamp: "yyyy-MM-dd HH:mm:ss"}]
}

### CODE REVIEW

**Comment by MetallicFocus** [comment]
Tested on the Android client and it receives a `java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "WebSocketWorker-10"` when sending a **login** request to the server. We have to investigate the issue before merging.

**Comment by ie208** [comment]
Thanks for pointing this out, I didn’t catch this with the test client. I’ll have a look at it tomorrow!

**Comment by MetallicFocus** [comment]
The error above was a result of the failure of getting the new `ChatMessage` java file by using the usual `git pull` command, which is rather interesting. After getting the file, it seems to work just fine.

**Comment by ie208** [comment]
I just pushed another change. I didn't realize it was going to add to this pull request!
New change is some cleaned up code and improved feedback to clients on failures: Previously some failures from DB operations such as login, register, or delete were only sending FAILURE and not sending any other information, now the exception message is also being retrieved.

**Pull request merged**
