### PR TITLE
Register users

### PR DESCRIPTION
**Pull request by EmadNaguiDarwish**

### CODE REVIEW

**Comment by Lotunnnnny** [comment]
It should be fine.

**Comment by MetallicFocus** [comment]
All good for now, just to make sure in some future commits to sort out possible SQL injection issues.

**Comment by EmadNaguiDarwish** [comment]
@MetallicFocus Ok will fix the SQL injection issues now before merging so it doesn't cause any problems in the future.

**Comment by MetallicFocus** [comment]
Great, I think it's all set now.

**Pull request merged**
