### PR TITLE
User left group and unregistered

### PR DESCRIPTION
**Pull request by EmadNaguiDarwish**
Adjusted the following methods:
- addUser()
- deleteUser()
- getAllUserInfo()
- getSearchedUsers()
- addNewGroup()
- addGroupMessage()
- addGroupMember()

### CODE REVIEW

**Comment by MetallicFocus** [comment]
I have conducted several tests on these changes and found the following:

1) If you unregister a user, you can **login with the same user again**.
2) If you unregister a user and try to register a new user with the same credentials, it will not allow you. (`java.sql.SQLException: Username already exists`)

**Comment by EmadNaguiDarwish** [comment]
1. Will fix it.
2. I think it shouldn't be allowed to register a user with the same credentials because this will result in a problem related to the history of messages and the chats with other users and the chats in the groups.

**Comment by MetallicFocus** [comment]
> 2. I think it shouldn't be allowed to register a user with the same credentials because this will result in a problem related to the history of messages and the chats with other users and the chats in the groups.

This is a valid point.

**Comment by EmadNaguiDarwish** [comment]
1 is now fixed.

**Pull request merged**
